apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 14
  selector: 
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: Recreate
  template: 
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx-opa
        resources:
          limits:
            cpu: "0.7"
            memory: 128Mi
          requests: 
            cpu: "0.3"
            memory: 64Mi
       